### ISSUE TITLE
Kickoff issue suggestion

### ISSUE THREAD

**Issue by jywarren** [publiclab/plotsbot#1]
Hi, @ryzokuken - i was thinking that the scenarios from your proposal could each (or the top ones people have liked) become an issue, or at least an item on your planning checklist. Checklists can be re-ordered easily, but just seeing them laid out could be really nice, and perhaps copying in the content of each scenario into an issue, and linking to that issue from the "main" checklist issue, could help organize your project. 

Also, i'm curious, is the code driving the current bot in the #publiclab-testing room documented anywhere, or is its "script" something you might add to the plotsbot repository?

**Comment by jywarren** [comment]
Also, as we just did at publiclab/leaflet.blurred-image, can you add the `first-timers-only` issue label? Thanks!

**Comment by ryzokuken** [comment]
@jywarren Added the `first-timers-only` label, and we already have a few predefined labels like `help wanted`, I guess I could make an issue for each of the scenario and tackle them one by one, what do you say?

**Comment by jywarren** [comment]
Sounds great! @ebarry be aware of this new repo, exciting!

**Comment by ebarry** [comment]
Wow great! exciting @ryzokuken :D

**Comment by jywarren** [comment]
Can we close this since the projects are now posted? https://github.com/publiclab/plotsbot/projects

Please do if so! Thanks!

**Comment by jywarren** [comment]
I guess I'd like a way to look at the overall progress. That'd be at https://github.com/publiclab/plotsbot/milestones, which looks great too!

**Comment by jywarren** [comment]
OK!
