### ISSUE TITLE
too many "looks like nobody's around just now" messages

### ISSUE THREAD

**Issue by pdurbin** [publiclab/plotsbot#108]
I've been hanging out in the main Public Lab chat room for a few weeks now and it's very nice except that plotbot keeps spamming the channel with "looks like nobody's around just now" messages. Examples below from https://gitter.im/publiclab/publiclab?at=5ae228a12d0e228d7bb6fb9d are highlighted in red:

<img width="675" alt="nobody" src="https://user-images.githubusercontent.com/21006/39407319-374230ac-4b92-11e8-952e-9bfc44c24008.png">

Please note that above I've also highlighted in green a welcome message from plotbot that I think should remain. It's nice to greet new people like this and remind the channel about the code of conduct.

**Comment by pdurbin** [comment]
@jywarren hi! I assume @ryzokuken would link you to #104 where the conversation about DMs as a solution is happening. In this issue I'm trying to be agnostic about the solution. :smile:

**Comment by ryzokuken** [comment]
@jywarren me and @pdurbin have been working on a pre-requisite step for it, by making an excel sheet full of alternative chat platforms.

My point here being: we'd first need to bring the community to a single unified platform in order to make DMs work. As of now, the community is fragmented, with plotsbot itself sticking to IRC, which means that it cannot DM non-irc users (the majority of them) and has to rely on sending messages on the channel, which remains the single common medium of communication between plotsbot and the user.

Once we choose to and move to an alternate medium, plotsbot would need a new interface (which shouldn't be too much work, thanks to our modularization work last summer), and added DM functionality which again, is trivial to develop.

Honestly speaking, the actual elephant in the room is the shift to a more appropriate communication medium.

**Comment by pdurbin** [comment]
Yes, I linked to the spreadsheet about various chat platforms in a comment with some additional context at https://github.com/publiclab/plots2/issues/2590#issuecomment-385257554

Here's a direct link to the spreadsheet: https://docs.google.com/spreadsheets/d/1V-L55OusMKgZNkbc_yarASQuWa9JoJzxkjqjCxfLOkw/edit?usp=sharing

**Comment by pdurbin** [comment]
@icarito you're saying that plotbot would be able to connect to as many chat services as Public Labs uses, right? It's not a bad idea but it would be a lot of work because so many services are used. As of this writing I believe they are Matrix, IRC, Gitter, and Slack.

**Comment by pdurbin** [comment]
It dawned on me today that plotsbot always gets the last word.

@icarito @ebarry and I can be chatting away for quite a while and say goodbye quite naturally but plotsbot always chimes ten minutes later saying that nobody's around:

<img width="463" alt="screen shot 2018-04-29 at 10 43 46 pm" src="https://user-images.githubusercontent.com/21006/39413897-e67ae6d8-4bfe-11e8-9c7f-8d90d7d196d5.png">

It makes me wonder what message we are trying to send. The message seems very well-intentioned. Presumably it's supposed to help newcomers to the channel know that we care what they think even if no one is available to chat. The newcomers are offered alternative ways to get in touch. But shouldn't channel regulars be free to converse and allow ten minutes to pass without receiving this message intended for newcomers? As the clock ticks I start feeling pressure to say something so that the bot doesn't interrupt the conversation. Can the bot track channel regulars and only send the "nobody's around" messages to the non-regulars? Or should we just kill the "nobody's around" message for now?

**Comment by jywarren** [comment]
Here's a very rough initial attempt at this behavior: https://github.com/publiclab/plotsbot/pull/109

I'm not great at this... any help appreciated!

**Comment by pdurbin** [comment]
@jywarren thanks so much for weighing in on this issue and making the pull request. I left a review on it.

> The "nobody's here" message (called the idle behavior) is triggered if someone asks something but doesn't get a response in 10 mins -- so newcomers don't feel unsupported if nobody's there to answer a question.

It's nice to hear the intent but the reality is somewhat different in the sense that people aren't necessarily asking questions. People are having a nice chat and ending with "whelp, good chat. good night!" But then plotbot always has to have the last word. "Nobody's around!" 😄 

Over in #openhatch of freenode Welcomebot has existed in various forms at various times and I like the model it uses where is remembers people by persisting their nicks in a file on disk (nicks.csv) and then never bothers them again. You can read about Welcombot at https://github.com/shaunagm/WelcomeBot

Just some thoughts for you. Thanks again for the pull request!

**Comment by pdurbin** [comment]
@ryzokuken @jywarren I just opened pull request #110 as another option. It disable's the "nobody's around" message for now.

**Comment by jywarren** [comment]
> persisting their nicks

Great - copying this segment over to #101 -- thanks!!! 👍 

And saw your review - double thanks!

**Comment by pdurbin** [comment]
Now that pull request #110 has been merged, it should be safe to close this issue, so I'll go ahead. Thanks for approving it @ryzokuken and for merging it @jywarren . Much appreciated.

**Comment by jywarren** [comment]
thank you too!
