### ISSUE TITLE
Add few more admins to publiclab-testing IRC channel

### ISSUE THREAD

**Issue by jywarren** [publiclab/plotsbot#113]
We had some ugly abuse just now, but only @ryzokuken is an admin on OFTC -- can you add @icarito and @jywarren and @ebarry?

**Comment by ryzokuken** [comment]
@jywarren will do this right now.

**Comment by ryzokuken** [comment]
@jywarren I added Sebastian, neither you nor Liz were on the channel right now. LMK whenever you can drop in for a moment and I'll be happy to OP you.
