### ISSUE TITLE
List out all the current FTO issues

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plotsbot#2]
Plotsbot should be able to list out all the available `first-timers-only` issues if the user asks for it. The question pattern could be like `@plotsbot fto`, but all ideas are welcome.

The bot should display `first-timers-only` issues from all the repositories from the publiclab organization if no specific repository was mentioned. Otherwise, it should only mention the `first-timers-only` issues from the repositories mentioned. For example, something like `@plotsbot fto plots2 webjack leaflet-blurred-location` should mention the issues from these three repositories only.

**Comment by ryzokuken** [comment]
@ananyo2012 @jywarren things have been a little low-profile lately. Should I start working on this?

**Comment by ananyo2012** [comment]
Yes sure Ujjwal. In the mean time we figure out how to use the Plots2 API
in the bot you can work on this till then.

**Comment by ryzokuken** [comment]
I think @jywarren would have to create an application on Github and get the required the keys being the owner of the organization. Meanwhile, I would register a makeshift key in my own name on Github.

**Comment by jywarren** [comment]
Happy to get keys when needed, but yes, until we have a more
feature-complete version running (say on the main chatroom) we can work
with a temporary key thats one of yours. Thanks!

**Comment by ryzokuken** [comment]
Resolved in #51
