### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plotsbot#27]
Hi, this is a [first-timers-only issue](https://github.com/publiclab/plots2/projects/2). This means we've worked to make it more legible to folks who **either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.**

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general help wanted issues. Thanks!

### The Problem

README badges are cool. Not only do they convey super-important information in a nutshell, they look great and add to the appeal of the README of a project.

### Solution

Add a badge to the README. The corresponding markdown code to be added for each badge can be found on [shields.io](https://shields.io/)

The README file: https://github.com/publiclab/plotsbot/blob/master/README.md

There are multiple places where these badges could be added:
1. Projects like [Express](https://github.com/expressjs/express) put the badges below the one-line description of the project. (Essentially between the description)
2. Projects like [Kotlin](https://github.com/JetBrains/kotlin) put the badges above the project header.
3. Most of facebook's projects like [React-Native](https://github.com/facebook/react-native) put the badges right next to the header.
4. Projects like [Visual Studio Code](https://github.com/Microsoft/vscode) put the badges right below the header and above the project description.

The list of badges to be added is:

- [x] TravisCI [![Build Status](https://travis-ci.org/publiclab/plotsbot.svg?branch=master)](https://travis-ci.org/publiclab/plotsbot)
- [x] Code Climate [![Code Climate](https://codeclimate.com/github/publiclab/plotsbot/badges/gpa.svg)](https://codeclimate.com/github/publiclab/plotsbot)
- [x] License [![License: GPL v3](https://img.shields.io/badge/License-GPL%20v3-blue.svg)](http://www.gnu.org/licenses/gpl-3.0)
- [x] Dependencies [![David](https://david-dm.org/publiclab/plotsbot.svg)]()
- [x] Git tag [![Git tag](https://img.shields.io/github/tag/publiclab/plotsbot.svg)]()
- [x] Coveralls [![Coveralls](https://img.shields.io/coveralls/publiclab/plotsbot.svg)]()
- [x] PRs welcome [![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](http://makeapullrequest.com) 

Generally, you would want to claim which one of the badges you would like to add to the README in the comments below and then submit a PR linking to this issue.

### Steps to Fix

- [ ]  claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] set up a repository locally following the README instructions, and make sure that all tests pass
- [ ] try to fix the issue following the steps above, but even before you're done, you can:
- [ ] commit your changes and start a pull request (see contributing to [Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] alert someone via the developers list (see below) to have your pull request merged. This may take a few extra steps depending on when you do it, but we'll help you out!

Please email the developers list (see https://publiclab.org/wiki/developers) or go to the [chatroom](https://publiclab.org/chat) if you have questions, and take a look at [our first-timers landing page for more information!](https://github.com/publiclab/plots2/projects/2)

**Comment by ananyo2012** [comment]
Ah this looks like a great FTO issue. can you reformat this in the FTO template?

**Comment by ryzokuken** [comment]
@ananyo2012 Sure, I will.

**Comment by jywarren** [comment]
+1 :-)

**Comment by ryzokuken** [comment]
@jywarren @ananyo2012 Look at this one and label it as an FTO if you guys find it appropriate. I feel that we can use this one as not one but six FTOs. We can definitely append to this list of badges later.

**Comment by ananyo2012** [comment]
Since these are small readme changes we can go on with a single PR. But again @jywarren can say it better :blush:

**Comment by jywarren** [comment]
I could go either way, but consider that the point of an FTO is not to
solve a problem efficiently (although that's a secondary goal) but to
engage new people into a project. So:

* 6 could engage more people, and since the formatting is nearly the same
for each, it's easy to make them all vs 6 completely novel ones
* but are we ready for 6 new people to join -- like are there other issues
they could work on once they finish these, or are you ready enough to
supply them when the time comes?

Maybe it could be done sequentially so you don't get 6 new contributors all
at once.

**Comment by ryzokuken** [comment]
@jywarren Exactly. Let's not expect that six new people would show up almost instantly. Also, if they do. We do have some stuff up our sleeve that we **might** have to rush to, but I don't think 
(A) It's a huge possibility. 
(B) It would be that difficult to add a few good level-2 issues. Probably a few features on the chatbot service.
Let's keep in mind that plots2 has been consistently making great FTOs and is thus pretty high up in online lists such as up-for-grabs.net. This repository does not enjoy such status yet.

**Comment by jywarren** [comment]
True. Great thinking ahead!

**Comment by ryzokuken** [comment]
@jywarren Then should we clear this and add the FTO label?

**Comment by jywarren** [comment]
once it has full checklist and docs, go for it. Or you can break out
sub-issues for each separate one if you want to do multiple, and track them
overall from here. Either way!

**Comment by ryzokuken** [comment]
One issue for each also sounds great. Although uptil now I wanted to use this single issue for all 6 FTOs. I will make 6 new issues today for each one. 

Is the checklist not complete? I copied it from an FTO at plots2.

**Comment by jywarren** [comment]
Yes, can you just linkify shields.io (it's not doing it automatically unfortunately) and link to the README file itself directly so it's even more explicit? You may want to indicate what line too. Thanks!

**Comment by jywarren** [comment]
Sorry i was replying via email so didn't see the checklist :-) Perfect

**Comment by ryzokuken** [comment]
Great. I will do those right now. Please add the label when you find the issue appropriate.

**Comment by ryzokuken** [comment]
@jywarren I added a few probable positions for the badge, let's decide which one would work best for us. Also, should we cleanup the issue by removing all the comments?

**Comment by jywarren** [comment]
sure, go ahead!

**Comment by ryzokuken** [comment]
Hello and welcome aboard, @Alhern!  
We would love to have you contribute to this issue.

In case you face any issues setting up the project locally or regarding anything else related, feel free to ask on this thread, or you could join (#publiclab on the OFTC IRC server)[http://chat.publiclab.org/] or the #publiclab matrix chatroom, or the (Gitter chatroom)[https://gitter.im/publiclab/publiclab], whichever you find convenient (all these rooms are linked so there's no difference whatsoever).

Also, I would be interested to know about how you came to know about us. This would go a long way towards making us friendlier and more appealing towards first-time contributors.

**Comment by Alhern** [comment]
Thanks a lot, @ryzokuken! 
I've found you by looking through the first timers only tag, I looked at your projects and read your readme's, I really liked how friendly and welcoming you were and this is why I decided to give it a try with a little pull request.

**Comment by ryzokuken** [comment]
That's wonderful, @Alhern.  
Looking forward to your PR.

**Comment by namansancheti** [comment]
Hi @ryzokuken,
I would like to claim the badge - 'License' and submit a Pull Request after adding it to the README.

**Comment by ryzokuken** [comment]
Hey @namansancheti!

That sounds awesome. Thanks for your contribution.

**Comment by namansancheti** [comment]
@ryzokuken Thanks a lot for accepting my Pull Request.
This was my first ever contribution!
Time to go for bigger contributions now..:D

**Comment by tracypholmes** [comment]
I would like to claim the **'PRs welcome'** badge, if it is still up for grabs!

**Comment by ryzokuken** [comment]
@tracypholmes it most certainly is! Thanks.

Do keep if informed if you face any problems in the process, and we will try to help you out to the best of our abilities.

Good luck.

**Comment by tracypholmes** [comment]
@ryzokuken thank you and hopefully it was done correctly. I appreciate your allowing me to do this!

**Comment by jywarren** [comment]
Thank you so much, Tracy! very cool and we'd love to work with you again here or at the main plots2 repository (https://github.com/publiclab/plots2).

**Comment by tracypholmes** [comment]
@jywarren that would be awesome! I will take a look at it this week as well.

**Comment by Delboyeire** [comment]
Hi, Could I take a shot at contributing to this? it would be my first :-)

**Comment by ryzokuken** [comment]
@Delboyeire sure. We would love to help you out.

Just choose one of the unchecked badges above and try adding it. Feel free to ask if you face any problems.

Thanks for taking an initiative.

**Comment by prabeous73** [comment]
Hi, I would like to attempt adding the 'Dependencies' badge if this issue is still open. It would be my first ever contribution.

**Comment by ryzokuken** [comment]
Hi, @prabeous73! Thanks for reaching out.

Yes, the dependencies badge is yet to be added, please feel free to give it a shot and ask if you face any issues.

**Comment by Big-Tom** [comment]
This would be my first contribution, but I can take a shot at the code climate badge.

**Comment by ryzokuken** [comment]
@Big-Tom thanks for approaching us, please feel free to make that change.

If you face any issues, feel free to ask us.

**Comment by Big-Tom** [comment]
I submitted a pull request for the badge, it should work properly.

**Comment by Uarmagan** [comment]
Hello, Could I add the Git tag? This is my first contribution as well. I'll go ahead and do the PR.

**Comment by ryzokuken** [comment]
@Uarmagan great! Please do.

Thanks for reaching out.

**Comment by ryzokuken** [comment]
Closing this as all tasks have been completed.

Thanks all!
