### ISSUE TITLE
Add "try it out here" demo

### ISSUE THREAD

**Issue by jywarren** [publiclab/plotsbot#33]
Do you think we could link to the demo here: https://riot.im/app/#/room/#publiclab-testing:matrix.org  from the README?

**Comment by ryzokuken** [comment]
We can definitely link the chatroom in the README. How is this different from #16 though?

**Comment by jywarren** [comment]
Oops, sorry you're right! Somehow i missed that. Reading too many PRs! Can
you close this then? Thanks.

**Comment by ryzokuken** [comment]
I will. I get it that you care about this. I will probably add this to the README in a PR today. Thanks

**Comment by jywarren** [comment]
:-) also just a bit forgetful, but thanks.
