### ISSUE TITLE
Add project to up-for-grabs.net

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plotsbot#37]
https://github.com/up-for-grabs/up-for-grabs.net#add-a-project

**Comment by ryzokuken** [comment]
Merged and done.

@jywarren we're live already. yay!

![screenshot_2017-06-15_15-00-12](https://user-images.githubusercontent.com/13121330/27174984-76487718-51db-11e7-89d9-650e6a95aebe.png)

**Comment by ananyo2012** [comment]
Thanks @ryzokuken for this awesome initiative 👍

**Comment by ebarry** [comment]
tweeted!
https://twitter.com/PublicLab/status/875363081119051776

**Comment by ryzokuken** [comment]
Thanks @ebarry!
