### ISSUE TITLE
Static text request/response in specs?

### ISSUE THREAD

**Issue by jywarren** [publiclab/plotsbot#40]
The specs for the chatbot look pretty good! 

https://github.com/publiclab/plotsbot/blob/master/spec/chatbot-spec.js

But I wonder if we're testing against its own interface too much... i think the expected response should perhaps be compared to a static string, to ensure we're not being circular. 

That would also make the tests human-readable -- i.e. you ask a phrase `chatbot help` and you get a response `How can I help you?` for example. 

Make sense?

**Comment by ananyo2012** [comment]
Yes I was in fact we can do that by testing the messageResponse function.
ᐧ

**Comment by jywarren** [comment]
Sorry, not sure I understood -- do you mean we should test both methods
against the same static expectation?

**Comment by ananyo2012** [comment]
What I meant was we can write `Utils-spec` and there we can test the `messageResponse` function against static text expectations. That should take care of it right?

**Comment by ryzokuken** [comment]
@ananyo2012 let's discuss this right now if you're free?

**Comment by jywarren** [comment]
Yes! Although it seems we should be making a folder for /behaviors/ in the
/spec/ folder and creating a unique spec for each behavior, under the new
architecture.

**Comment by ryzokuken** [comment]
I made utils thinking I would add functions in it that would be general utilities across all services, but ended up adding the complete help functionality there. Its not appropriate place for those functions. I think placing those functions in the appropriate place and keeping `utils.js` for functions that are general utilities only would work best for us.

**Comment by jywarren** [comment]
Yes, i think `utils.js` is appropriate for some things, but if you move all
`help` methods into a `help.js` behavior, and both the behavior-related
methods into `behaviors.js`, theres not a lot left in `utils.js` -- but
that's fine. Small is good!

**Comment by ryzokuken** [comment]
@jywarren I think the new tests I wrote satisfy these requirements. I have generated the raw strings using the `helpMessage` function and compared the response to them rather than using function calls. Should we close this now?

**Comment by jywarren** [comment]
I saw that the input text was static, but not the response text -- unless
maybe I missed something. I think we should test both against static
strings, so the exact wording of call/response is clear to someone reading
the test -- is that OK? Thanks!

**Comment by ryzokuken** [comment]
@jywarren 

```js
const chatbotHelp = helpMessage(botNick, 'chatbot');
const invalidHelp = helpMessage(botNick, 'invalid');
```

the `helpMessage` function is absolutely as low level as it gets. This function is returning the help texts for each module. I used this as manually writing matching help texts would get too tedious. Especially later when we have tons of behaviors to test. Here's how the function looks:

```js
function helpMessage (name, service) {
  let out = `# ${service}\n`;

  switch (service) {
  case 'chatbot':
    out += `\`${name} help [<module>...]\`: Prints out this descriptive help message for each mentioned module. If no modules are specified, print the help message for ALL modules.`;
    break;
  default:
    out += `\`${service}\` is not the name of a valid module. Try looking up the \`chatbot\` module instead.`;
  }

  return out;
}
```

just one level above manually setting the text string. But if you're still dissastisfied, I will add the strings.

**Comment by jywarren** [comment]
I see what you're saying, but we're then testing an input against another function whose output is not purely static. `helpMessage` does some string manipulation, so it should be tested as well -- it's not just a matter of using it as a helper. 

I think we could use it as a helper in some tests, but at some point it has to be asserted/compared against a static string to ensure it's inserting parameters correctly. What if someone broke the `helpMessage()` function? Would anyone notice, since the message it generates is being tested against itself generating that message?

**Comment by jywarren** [comment]
I guess maybe it's possible I'm being too extreme. 

Let's say that at least, when you call `  const chatbotHelp = helpMessage(botNick, 'chatbot');` the string `chatbot` is not enough for a reader to know that it's the right message. And since it's not in the same test, it's not as easy to read over the test and really know, quickly, that the chatbot will respond in an expected way. What do you think?

**Comment by jywarren** [comment]
Like, reading these: https://github.com/publiclab/plotsbot/blob/master/spec/help-spec.js#L16

I wonder why line 11 and 16 both return the same thing:

`  it('should print specific help for existing modules', () => {`

vs

`  it('should print specific help for nonexisting modules', () => {`

Maybe even without hard-coding the strings, using a more descriptive string to describe what the output will be, and moving the line `  const chatbotHelp = helpMessage(botNick, 'chatbot');` right before its use, would make this read more clearly.

**Comment by ryzokuken** [comment]
@jywarren I understand. I will swap the variables with their static counterparts.

**Comment by gauravano** [comment]
@jywarren @ryzokuken any particular issue you want to open from here? Thanks!

**Comment by jywarren** [comment]
I believe we can close this as there is now a `SimpleBehavior` class which can be used to generate a simple static response:

**Comment by jywarren** [comment]
https://github.com/publiclab/plotsbot/blob/9bfe117322bea5a806c1600db2c54ad5395a850f/src/bot.js#L53

**Comment by jywarren** [comment]
Although perhaps it could be added to the docs if it's not already!
