### ISSUE TITLE
Use a more approprimate format for the config file

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plotsbot#45]
When the project was created, I stored the configuration object inside a `js` file because it was most convenient to store the config inside a static object and export it to later conveniently `require` the configuration.

However, now I strongly feel that we should switch to a more sane format for storing configurations. Not only would it be better, but the file would also "look" more like a configuration file. We have the following options:

1. JSON (JavaScript Object Notation): One of the most obvious ways to store data, it is used by the npm package manager as well as ESLint and Jasmine (and pretty much every other package in the node ecosystem). However, I am not in favor of using a JSON file to store data because it is also a pretty nondescript format just like the current file.

2. YAML (YAML Ain't Markup Language): Used by travis and others, claims to be human readable.

3. TOML (Tom's Obvious Markup Language): Used by many popular tools, as the name suggests, it's dead obvious. This is the format that I prefer.\

4. XML (eXtensible Markup Language): Don't know. Honorable mention?

**Comment by ryzokuken** [comment]
@publiclab/soc your thoughts on this?

**Comment by jywarren** [comment]
JSON! Strong preference as it's much more adaptable to a javascript-only
environment, if we ever wanted to run these modules in the browser, for
example.

**Comment by ryzokuken** [comment]
@jywarren great. Then JSON seems the way to go.

**Comment by ananyo2012** [comment]
+1 for JSON

**Comment by ryzokuken** [comment]
@ananyo2012 JSON it is, then. I have a PR open. Look into it, I'll submit one for this then. Thanks :)

**Comment by ananyo2012** [comment]
Closed by #47
