### ISSUE TITLE
A behavior that responds if someone says something in a chatroom but doesn't get a response for 10m

### ISSUE THREAD

**Issue by jywarren** [publiclab/plotsbot#55]
It could say `if you haven't gotten a response, maybe post a question on PublicLab.org/questions` -- though it'd probably not want to say that if the person is in the chatroom a lot... only newcomers if theres any way to determine this.

**Comment by ryzokuken** [comment]
@jywarren cool. I will think over implementing this today.

**Comment by jywarren** [comment]
You'd suggested using a setTimeout, would that work?

**Comment by ryzokuken** [comment]
@jywarren It should, but for that I think we need another class of behaviors, `daemons`, that behave as the name suggests and work in the background. We could discuss this together whenever you're free and I would then love to implement this one ASAP.

**Comment by ryzokuken** [comment]
Resolved in #76 😄
