### ISSUE TITLE
`show` and `tell` from the cli

### ISSUE THREAD

**Issue by icarito** [publiclab/plotsbot#68]
* `show` should publish a paste and post a link to the irc channel ( icarito@tycho posted thisfile.txt to http://paste... )
* `tell` should tell a specific user (or all) a message, from the cmd line

**Comment by ryzokuken** [comment]
I think for this, we would need to run a local HTTP server that accepts request, and then make a little CLI client capable of these tasks that can send a request to the HTTP server, which will then send a message to IRC.

@jywarren @icarito @ananyo2012 there must be a better way to do it, what do you guys think?

**Comment by ryzokuken** [comment]
Or better still, we could use websockets.
