### ISSUE TITLE
About or Introduce behavior

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plotsbot#69]
A behavior in which you could ask plotsbot to introduce/identify itself. Mainly, I was interested to ask a plotsbot instance which version it was on.

I think it would be really useful, especially when there are some issues and you want to check the current version to determine if that bug has been fixed already and stuff like that.

@jywarren @ananyo2012 @icarito any thoughts?

**Comment by ananyo2012** [comment]
+1

**Comment by ryzokuken** [comment]
@ananyo2012 @jywarren thinking of working on this next. What should be the keyword for this behavior?

**Comment by jywarren** [comment]
This sounds nice, maybe `plotsbot version`? It'd show up in the help
command, right?

**Comment by ryzokuken** [comment]
@jywarren It should. That said, we have changed quite a few things and we haven't updated the `help` behavior from quite sometime. Could you make an issue for it? If you're busy, I would make one tonight.

**Comment by jywarren** [comment]
ok!

**Comment by ryzokuken** [comment]
Thanks :)
