### ISSUE TITLE
Use an appropriate testing framework

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plotsbot#7]
In order to make the project robust and avoid any major bugs, we need to have good test coverage. Therefore, I find it convenient to include and make use of a testing framework from this very early stage so that we can write tests as we go.

When it comes to backend test frameworks for Node JS, we have 3 major choices:
* Mocha
* Jest
* Jasmine

Removed from the list:
* Chai
* should.js

[My bad, these two are actually assertion libraries suitable for use with Mocha (Jasmine has its own assertions) and not actual testing frameworks]

Over the coming few days, we need to decide the most appropriate testing framework for the project and start using it.

Suggestions and help from @publiclab/soc appreciated.

**Comment by jywarren** [comment]
Hi, Ujjwal - i've mentioned that while Jasmine is great esp. since makes
for consistency across PL projects, it's primarily a browser-based test
system. I also suggested `tape` which we've used in image-sequencer -- it's
really really minimal, but more general purpose:

https://github.com/publiclab/image-sequencer/blob/master/package.json#L7

Can you start collecting some pros/cons to the top choices?

**Comment by ryzokuken** [comment]
@jywarren Yes. Over the next day or two, I intend to make a few notes here over the pros and cons of each testing framework so that everyone else can look into them and help decide.

**Comment by jywarren** [comment]
Great, sounds like this is coming along. Once tests start to be used, each test can illustrate a Behavior, and the Behavior section of the README could link to the tests code to illustrate how a behavior plays out. Make sense? That way the tests help to illustrate the functionality in a readable way. :-)

@david-days - it'd be cool if, to some degree, the API tests on plots2 were structured similarly. I"m not quite caught up on your work but will asap!

**Comment by ryzokuken** [comment]
@jywarren I am almost done setting up Jasmine with the project. Will make a PR for that and then tomorrow (hopefully, your tonight) make a PR with tests for the current behaviors. One thing I wanted to clarify was the naming of the different specs. Do I named the spec files like `spec/GithubSpec.js` or like `spec/github-spec.js`? So basically, do I name them in capitalized camelcase or in kebab case?

**Comment by jywarren** [comment]
i hadn't heard the term "kebab case" but that's great. You know, it's up to
you, i don't have a strong preference!
