### ISSUE TITLE
Simple "keyword/response" mini-behaviors

### ISSUE THREAD

**Issue by jywarren** [publiclab/plotsbot#95]
In Slack, the `slackbot` can be configured to respond to a list of keyword triggers in a simple format, where you type the trigger words and then the string that's returned:

* `cat` => `Hi there, a cat is a pet.`
* `file an issue` => `Want to file a GitHub issue? https://github.com/publiclab/plots2/issues/`

It'd be great to be able to add simple behaviors to `plotsbot` by just adding a single line like this to a "keywords" list. What do you think?

**Comment by ryzokuken** [comment]
Sure! We could modify the core to make it accept an array of strings for a behavior as compared to a single string or sth and then make a behavior that can accept multiple triggers.

Or perhaps add another function in the core to aid the programmer in adding simpler mini-behaviors?

**Comment by jywarren** [comment]
Which do you think would make for the simplest way to submit a new
behavior? I imagine even a one-line change could be possible, no?

**Comment by jywarren** [comment]
Also, potentially as a next step a function could be passed instead of a
response string and it could produce a simple dynamic response, like:

```
"trigger phrase": function response(user, message) { return responseString;
}
```

But simple string response is even easier as a first step.

I think doing this could be a great way to encourage new behavior
submission and start getting more people working on plotsbot - a nice
simple onramp!

**Comment by ryzokuken** [comment]
@jywarren sounds great! Let me dive into it.

**Comment by jywarren** [comment]
Awesome!!!
